as yet unclassified
topez: aTDTopezServer clientListBlock: clientListBlock menuActionSpecBlock: menuActionSpecBlock menuActionBlock: menuActionBlock itemSelectedBlock: itemSelectedBlock
  ^ self
    topez: aTDTopezServer
    clientListBlock: clientListBlock
    menuActionSpecBlock: menuActionSpecBlock
    menuActionBlock: menuActionBlock
    itemSelectedBlock: itemSelectedBlock
    keyboardActionBlock: nil
    windowIsClosingBlock: nil