project api
projectNew: projectName projectEntryPath: projectEntryPath packageName: packageName gitRootPath: gitRootPath applicationClassCreationBlock: applicationClassCreationBlock
  ^ self
    projectNew: projectName
    projectEntryPath: projectEntryPath
    packageName: packageName
    gitRootPath: gitRootPath
    superclassName: 'Object'
    applicationClassCreationBlock: applicationClassCreationBlock