project api
projectNew: projectName projectEntryPath: projectEntryPath packageName: packageName gitRootPath: gitRootPath requiredProjects: requiredProjects dependencies: dependencies repositories: repositories superclassName: superclasName applicationClassCreationBlock: applicationClassCreationBlock
  ^ self
    projectNew: projectName
    projectEntryPath: projectEntryPath
    packageName: packageName
    gitRootPath: gitRootPath
    requiredProjects: requiredProjects
    dependencies: dependencies
    repositories: repositories
    superclassName: superclasName
    applicationClassCreationBlock: applicationClassCreationBlock
    force: false