accessing
menuMapList
  ^ {('GemTools Launcher Menu' asText allBold).
  (' Transactions' asText allBold).
  '  Commit'.
  '  Abort'.
  '  Auto Abort'.
  '  Auto Commit'.
  '  Auto Migrate'.
  (' Find' asText allBold).
  '  Class...'.
  '  Hierarchy Browser...'.
  '  Class References...'.
  '  Method...'.
  '  String...'.
  '  Senders...'.
  '  Case Sensitive String...'.
  (' Tools' asText allBold).
  '  System Browser'.
  '  Open Workspaces'.
  '  File Browser'.
  '  Process Browser'.
  '  Inspect UndefinedSymbols'.
  '  Inspect Sent But Not Implemented'.
  '  Test Runner'.
  '  Monticello'.
  (' Admin' asText allBold).
  ('  Repository' asText allBold).
  '   List backup files'.
  '   Backup'.
  '   Restore from Backup'.
  '   Mark for Collection'}