accessing
menuMapList
  ^ {'GemTools Launcher Menu'.
  ' Transactions'.
  '  Commit'.
  '  Abort'.
  '  Auto Abort'.
  '  Auto Commit'.
  '  Auto Migrate'.
  ' Find'.
  '  Class...'.
  '  Hierarchy Browser...'.
  '  Class References...'.
  '  Method...'.
  '  String...'.
  '  Senders...'.
  '  Case Sensitive String...'.
  ' Tools'.
  '  System Browser'.
  '  Open Workspaces'.
  '  File Browser'.
  '  Process Browser'.
  '  Inspect UndefinedSymbols'.
  '  Inspect Sent But Not Implemented'.
  '  Test Runner'.
  '  Monticello'}