*topez-client-gemstone
sessionDescription3101tODE
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGCustomSessionDescription new
    name: 'tode';
    gemstoneVersion: '3.1.0.1';
    gciLibraryName: 'libgcirpc-3.1.0.1-32.so';
    adornmentColor: Color lightBlue;
    stoneHost: 'localhost';
    stoneName: 'seaside31';
    gemHost: 'localhost';
    netLDI: '50377';
    gemTask: 'gemnetobject';
    userId: 'tode';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself