*topez-client-gemstone
sessionDescription32_mac
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGCustomSessionDescription new
    name: '3.2_mac';
    gemstoneVersion: '3.2';
    gciLibraryName: 'libgcirpc-3.2.0-32.dylib';
    adornmentColor: Color lightGreen;
    stoneHost: 'localhost';
    stoneName: 'tode_32';
    gemHost: 'localhost';
    netLDI: '50377';
    gemTask: 'gemnetobject';
    userId: 'DataCurator';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself