*topez-client-gemstone
sessionDescription3101_mac
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGCustomSessionDescription new
    name: '3.1.0.1_mac';
    gemstoneVersion: '3.1.0.1';
    gciLibraryName: 'libgcirpc-3.1.0.1-32.dylib';
    adornmentColor: Color lightGreen;
    stoneHost: 'localhost';
    stoneName: 'seaside31';
    gemHost: 'localhost';
    netLDI: '50377';
    gemTask: 'gemnetobject';
    userId: 'DataCurator';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself