session descriptions
sessionDescription_c3101
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGStandardSessionDescription new
    name: 'c_gs64stone_3101';
    gemstoneVersion: '3.1.0.1';
    gciLibraryName: 'libgcirpc-3.1.0.1-32.so';
    adornmentColor: Color lightYellow;
    stoneHost: 'foos.gemstone.com';
    stoneName: 'c_gs64stone_3101';
    gemHost: 'foos.gemstone.com';
    netLDI: '33066';
    userId: 'DataCurator';
    password: 'swordfish';
    backupDirectory: '';
    yourself