session descriptions
sessionDescription32_foos
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGCustomSessionDescription new
    name: '3.2_foos';
    gemstoneVersion: '3.2';
    gciLibraryName: 'libgcirpc-3.2.0-32.dylib';
    adornmentColor: Color lightYellow;
    stoneHost: 'foos.gemstone.com';
    stoneName: 'k_gs64stone';
    gemHost: 'foos.gemstone.com';
    netLDI: '38352';
    gemTask: 'gemnetobject';
    userId: 'DataCurator';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself