as yet unclassified
mmbManPage
  ^ 'NAME
  mmb - metacello baseline commands

SYNOPSIS

  mmb baseline <baseline-name> <section> <baseline-reference-name> 
              [loads <name-list>]
              [postload <postload-selector>]
              [preload <preload-selector>]
              [repository <repo-spec>]
  mmb browse <baseline-name> 
              [group <group-names>]
              [package <package-names>]
              [project <project-names>] 
  mmb configuration <baseline-name> <section> <configuration-reference-name> 
              [loads <name-list>]
              [postload <postload-selector>]
              [preload <preload-selector>]
              [repository <repo-spec>]
              [version <version-number>]
  mmb create <baseline-name>
  mmb group <baseline-name> <section> <group-name> [<name-list>]
  mmb names <baseline-name> [<section>]
  mmb package <baseline-name> <section> <package-name> 
              [file <package-file-name>]
              [includes <package-name-list>]
              [postload <postload-selector>]
              [preload <preload-selector>]
              [repository <repo-spec>]
              [requires <package-name-list>]
  mmb postload <baseline-name> <section> <postload-selector>
  mmb preload <baseline-name> <section> <preload-selector>
  mmb repository <baseline-name> <repo-spec>

DESCRIPTION
'