SystemOrganization addCategory: #'Tode-Minimal-Client-Debugger'!
SystemOrganization addCategory: 'Tode-Minimal-Client-Debugger-Announcements'!
SystemOrganization addCategory: 'Tode-Minimal-Client-Debugger-ClientElements'!
SystemOrganization addCategory: 'Tode-Minimal-Client-Debugger-Inspector'!
SystemOrganization addCategory: 'Tode-Minimal-Client-Debugger-Presentations'!
SystemOrganization addCategory: 'Tode-Minimal-Client-Debugger-Renderer'!
