as yet unclassified
deployManPage
  ^ 'NAME
  deploy - deploy FileTree pacakges to mcz repository

SYNOPSIS
  deploy [<update-repo>]

DESCRIPTION

  <update-repo> is `true` or `false`.

  ./tmpGitRepo :: directory path for https://github.com/dalehenrich/filetree clone

    /opt/git/tmp/filetree

  ./target :: url of http://ss3.gemstone.com/ss/FileTree

    http://ss3.gemstone.com/ss/FileTree
    filetree:///opt/git/tmp/filetree
'