built-ins
help
	^self openWorkspace: '
Thank you for trying tODE.
--------------------------

The best way to get going with tODE is to follow the instructions on the 
gsDevKitHome project site[1] for installing and setting up GemStone.

Then take a look at "Getting Started with tODE"[2].

[1] https://github.com/GsDevKit/gsDevKitHome#open-source-development-kit-for-gemstones-64-bit-
[2] https://github.com/dalehenrich/tode/blob/master/docs/GettingStarted.md#getting-started-with-tode

' label: 'Help for tODE'.
