accessing
sessionDescription2441_mac
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGCustomSessionDescription new
    name: '2.4.4.1_mac';
    gemstoneVersion: '2.4.4.1';
    gciLibraryName: 'libgcirpc64-244.so';
    adornmentColor: Color lightRed;
    stoneHost: 'localhost';
    stoneName: 'seaside';
    gemHost: 'localhost';
    netLDI: '57643';
    gemTask: 'gemnetobject';
    userId: 'DataCurator';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself