accessing
menuMapList
  ^ {('GemTools Launcher Menu' asText allBold).
  (' Transactions' asText allBold).
  '  Commit'.
  '  Abort'.
  '  Auto Abort'.
  '  Auto Commit'.
  '  Auto Migrate'.
  (' Find' asText allBold).
  '  Class...'.
  '  Hierarchy Browser...'.
  '  Class References...'.
  '  Method...'.
  '  String...'.
  '  Senders...'.
  '  Case Sensitive String...'.
  (' Tools' asText allBold).
  '  System Browser'.
  '  Open Workspaces'.
  '  File Browser'.
  '  Process Browser'.
  '  Inspect UndefinedSymbols'.
  '  Inspect Sent But Not Implemented'.
  '  Test Runner'.
  '  Monticello'.
  (' Admin' asText allBold).
  ('  Repository' asText allBold).
  '   List backup files'.
  '   Backup'.
  '   Restore from Backup'.
  '   Mark for Collection'.
  ('  DoIt' asText allBold).
  '   Changed packages & methods'.
  ('   Configuration Reports' asText allBold).
  '    Gem Configuration Report'.
  '    Stone Configuration Report'.
  '   Empty Object Log'.
  '   File Size Report'.
  '   Object Log'.
  '   User Session Report'.
  ('   Version Report' asText allBold).
  '    Client Version Report'.
  '    Gem Version Report'.
  '    Stone Version Report'.
  '  Browser Preferences'.
  '  Commit on Almost Out of Memory'.
  '  Popup on debug'.
  '  Send Bug Report'.
  ' Help'.
  (' Debug...' asText allBold).
  '  Remove Continuations from Object Log'.
  '  Clear Object Log'.
  '  Debug Continuations'.
  (' Update...' asText allBold).
  '  Update GemTools Launcher'.
  '  Update GLASS'}