accessing
sessionDescription_c3101_mac
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGStandardSessionDescription new
    name: 'c_gs64stone_3101_mac';
    gemstoneVersion: '3.1.0.1';
    gciLibraryName: 'libgcirpc-3.1.0.1-32.dylib';
    adornmentColor: Color lightYellow;
    stoneHost: 'foos.gemstone.com';
    stoneName: 'c_gs64stone_3101';
    gemHost: 'foos.gemstone.com';
    netLDI: '58919';
    userId: 'DataCurator';
    password: 'swordfish';
    backupDirectory: '';
    yourself