accessing
sessionDescription32_mac
  "self initializeSessionMap"

  <sessionDescription>
  ^ OGCustomSessionDescription new
    name: '3.2_mac';
    gemstoneVersion: '3.2';
    gciLibraryName: 'libgcirpc-3.1.0.1-32.dylib';
    adornmentColor: Color lightGreen;
    stoneHost: 'localhost';
    stoneName: 'tode_32';
    gemHost: 'localhost';
    netLDI: '49751';
    gemTask: 'gemnetobject';
    userId: 'DataCurator';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself