accessing
sessionDescription_k_mac
  ^ OGStandardSessionDescription new
    name: 'k_gs64stone_mac';
    gemstoneVersion: '3.2';
    gciLibraryName: 'libgcirpc-3.2.0-32.dylib';
    adornmentColor: Color lightGreen;
    stoneHost: 'foos.gemstone.com';
    stoneName: 'k_gs64stone';
    gemHost: 'foos.gemstone.com';
    netLDI: '54174';
    userId: 'DataCurator';
    password: 'swordfish';
    backupDirectory: '';
    yourself