accessing
sessionDescription_r_mac
  ^ OGStandardSessionDescription new
    name: 'r_gs64stone_mac';
    gemstoneVersion: '3.1.0.3';
    gciLibraryName: 'libgcirpc-3.1.0.3-32.dylib';
    adornmentColor: Color lightRed;
    stoneHost: 'foos.gemstone.com';
    stoneName: 'r_gs64stone';
    gemHost: 'foos.gemstone.com';
    netLDI: '49352';
    userId: 'DataCurator';
    password: 'swordfish';
    backupDirectory: '';
    yourself