accessing
sessionDescription3101sample
  ^ OGCustomSessionDescription new
    name: 'sample';
    gemstoneVersion: '3.1.0.1';
    gciLibraryName: 'libgcirpc-3.1.0.1-32.so';
    adornmentColor: Color lightGreen;
    stoneHost: 'localhost';
    stoneName: 'seaside31';
    gemHost: 'localhost';
    netLDI: '50377';
    gemTask: 'gemnetobject';
    userId: 'sample';
    password: 'swordfish';
    osUserId: '';
    osPassword: '';
    backupDirectory: '';
    dataDirectory: '';
    yourself