accessing
todeServerAPIVersionString
  "Version changes whenever the api between client and server changes:
   Major version changes when incompatible API changes have been made.
   Minor version changes when API is extended/changed in a backwards compatible manner.
   Patch version changes whenever bugfixes are made in the API"

  "1.0.0 - initial version"

  "1.1.0 - introduce TDEventsCache"

  ^ '1.1.0'