initialization
initializeCities
	cities := Dictionary new.
	cities at: 'Santiago' put: -33.4500 @ -70.66.
	cities at: 'Vina del Mar' put: -33 @ -71.52.
	
	cities at: 'New York City' put: 40.67 @ -73.94 .
	cities at: 'Washington, D.C.' put: 38.89 @ -77.03.
	cities at: 'Paris' put: 48.85 @ 2.35.
	cities at: 'Nice' put: 43.70 @ 7.26.
	cities at: 'Bordeaux' put: 44.84 @ -0.58.

	cities at: 'Bogota' put: 4.5981 @ -74.07.
	cities at: 'Buenos Aires' put: -34.60 @ -58.38.
	cities at: 'Brasilia' put: -15.79 @ -47.86.
	cities at: 'Sao Paulo' put: -23.55 @ -46.63.
	cities at: 'Montevideo' put: -34.88 @ -56.18.
	cities at: 'Lima' put: -12.04 @ -77.03.
	cities at: 'La Paz' put: -16.5 @ -68.15.
	cities at: 'Quito' put: -0.25 @ -78.58.
	cities at: 'Caracas' put: 10.5 @ -66.92.
	
	cities at: 'Shanghai' put: 31.2 @ 121.5.