as yet unclassified
commitVersion: version baseVersionNumber: baseVersionNumber branch: branch author: author into: targetRepo repositoryGroup: repositoryGroup commitMessage: commitMessage
  ^ (self topez toolInstanceFor: 'mc')
    commitVersion: version
    baseVersionNumber: baseVersionNumber
    branch: branch
    author: author
    into: {targetRepo}
    repositoryGroup: repositoryGroup
    commitMessage: commitMessage