as yet unclassified
clsManPage
  ^ 'NAME
  cls - class manipulation support

SYNOPSIS
  cls accessors <class-name> [ instance|class ]
      accessors @<class-path> [ instance|class ]
  cls comment <class-name>
      comment @<class-path>
  cls copy <class-name> <new-name>
      copy @<class-path> <new-name>
  cls create <class-name> [ <superclass-name> [ <category> ] ]
      create <class-name> [ @<superclass-path> [ <category> ] ]
  cls definition <class-name>
      definition @<class-path>
  cls history <class-name>
      history @<class-path>
  cls rename <old-name> <new-name>
      rename @<class-path> <new-name>
  cls remove <old-name>
      remove @<class-path>

DESCRIPTION
'