as yet unclassified
protocolManPage
  ^ 'NAME
  protocol - manage method protocol

SYNOPSIS
  protocol add <class-name> <protocol-name>
           add @<class-path> <protocol-name>
  protocol cadd <class-name> <protocol-name>
           cadd @<class-path> <protocol-name>
  protocol cremove <class-name> <protocol-name>
           cremove @<class-path> <protocol-name>
  protocol crename <class-name> <protocol-name> <new-protocol-name>
           crename @<class-path> <protocol-name> <new-protocol-name>
  protocol remove <class-name> <protocol-name>
           remove @<class-path> <protocol-name>
  protocol rename <class-name> <protocol-name> <new-protocol-name>
           rename @<class-path> <protocol-name> <new-protocol-name>

DESCRIPTION
'