license and info
roassalDescription
	^ 
'Roassal graphically renders objects using short and expressive Smalltalk expressions. 
A large set of interaction are offered for a better user experience. Painting, brushing, interconnecting, 
zooming, drag and dropping will just make you more intimate with any arbitrary object model.

Information about Roassal may be found online: http://objectprofile.com

Follow us on Twitter: @ObjectProfile

Facebook page: http://facebook.com/ObjectProfile
'

