as yet unclassified
beditManPage
  ^ 'NAME
  bedit - batch edit tool

SYNOPSIS
  bedit class <className> <source-regex> <replacement-string>
  bedit instance <className> <source-regex> <replacement-string>
  bedit list <definitionList-path> <source-regex> <replacement-string> 
  bedit references <globalNameOrPathRef>  <source-regex> <replacement-string> 
  bedit method <selector> <source-regex> <replacement-string>
  bedit rmethod <regex-pattern> <source-regex> <replacement-string>
  bedit rsender <regex-pattern> <source-regex> <replacement-string>
  bedit sender <selector> <source-regex> <replacement-string>
  bedit source <regex-pattern> <source-regex> <replacement-string>

DESCRIPTION

  CMD-g - go to next match
  CMD-j - perform replace, go to next match
'