accesing
packages
	 ^ {
		'Trachel'->{'Core'. 'Viva'}.
		'Roassal2'->{
			'Builder-AnimatedScatterPlot'. 'Builder-AxisAdapted'.
			'Builder-BoxPlot'.
			'Builder-CircularMap'. 'Builder-Common'.
			'Builder-Composer'. 'Builder-Explora'.
			'Builder-Grapher-Core'. 'Builder-Grapher-Decorators'.
			'Builder-Grapher-Obsolete'. 'Builder-Grapher-Tests'.
			'Builder-Kiviat'. 'Builder-Legend'. 
			'Builder-Map'. 'Builder-Map-Tests'. 'Builder-Menu'.
			'Builder-Mondrian'. 'Builder-MondrianOLD'. 'Builder-NameCloud'.
			'Builder-PieChart'. 'Builder-ScatterplotMap'. 
			'Builder-ScrollBar'. 'Builder-SimilarityMatrix'.
			'Builder-Simon'. 'Builder-Spectrograph'. 
			'Builder-StackBarPlot'. 'Builder-StructureMatrix'.
			'Builder-Sunburst'. 'Builder-TextBuilder'.
			'Builder-TimeLine'. 'Builder-TimeLine-Tests'. 'Builder-TreeMap'.
			'Builder-UI-Slider'. 'Builder-UML'. 
			'Cachetor'. 'ColorNormalizer'.
			'Core'. 'Core-Tests'. 'ExampleBrowser'.
			'Exporter-HTML5'. 'Exporter-PNG'. 'Exporter-SVG'. 'Layouts'. 'OpenStreetMap'.
			'Selection'. 'Sparkline'. 'Table'. 'Tests'. 'Utility'}
		}