icons
exampleMovingCameraIcon
	^ 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABjCAYAAABt56XsAAABj0lEQVR4XuXVIU+CURgFYJOF
TzY3JsFNNzc3i2wEA6MatJMcweAcFIk6ihuFgNViwPEfDCT+AM0RIJGtGrTpNbB9YwiFfeCe
ZzvhvvGccDd8Pt8S7YdEU7c9v5blu55xOww5mrqVQyqx907IuV/fcl2EXIUcxG7bIYWQs5B0
7H4ccuNX5vP5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6f
z+fz+Xy+/yybze7mcrkTv4kVq1Qqt/1+/208Hn9PUq/XH6IoSvvtJKzRaDzGh4in1+uNNgO/
pYTk8/nCX2NM0ul0un5TCWm1Ws+LBvmN31RCBoPBuz/IGul2u6/+IGukWq3eLRpjOBx++k0l
aDQafc0bpFgsnvotJSiTyWTDX/Ixa4xSqXTpN7Qi5XK52mw2n9rt9kutVrtPpVJbfis+n8/n
8/l8Pp/P5/P5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6fz+fz+Xw+n8/n8/l8Pp/P5/P5fD6f
zzffDyz/G9+Gw2cAAAAAAElFTkSuQmCC'